
// Objective-C API for talking to the following Go packages
//
//	openpano-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Openpano_FRAMEWORK_H__
#define __Openpano_FRAMEWORK_H__

#include "Openpano.objc.h"
#include "Universe.objc.h"

#endif
